INSERT INTO Station(Bezeichnung) VALUES("Innere Medizin");
INSERT INTO Person(Vorname, Nachname, Adresse, Geschlecht, Geburtsdatum) 
	VALUES("Janes", "Heuberger", "Schutterwald", "m", DATE("1994-09-01")),
	VALUES("Klaus", "Arendt", "Ohlsbach", "m", DATE("1991-05-03")),
	VALUES("Joachim", "Adam", "Offenburg", "m", DATE("1992-04-03")),
	VALUES("Thomas", "Adolf", "Freiburg", "m", DATE("1997-02-04")),
	VALUES("Liliane", "Bauer", "Freiburg", "w", DATE("1984-05-05")),
	VALUES("Lukas", "Brau", "Offenburg", "m", DATE("1964-09-06")),
	VALUES("Samuel", "Burg", "Waldkirch", "m", DATE("1962-08-07")),
	VALUES("Matthias", "Bruggmoser", "Waldkirch", "m", DATE("1959-07-08")),
	VALUES("Arianna", "Adari", "Offenburg", "w", DATE("1950-09-12")),
	VALUES("Arion", "Cern", "Freiburg", "m", DATE("1954-11-30")),
	VALUES("Brigitte", "Dahlmann", "Lahr", "w", DATE("1953-10-29")),
	VALUES("Bruno", "Danner", "Waldkirch", "m", DATE("1958-11-15")),
	VALUES("Doreen", "Dannecker", "Offenburg", "w", DATE("1957-09-19")),
	VALUES("Dan", "Erdmann", "Freiburg", "m", DATE("1991-07-11")),
	VALUES("Elena", "Emmenecker", "Waldkirch", "w", DATE("1990-07-21")),
	VALUES("Irina", "Freud", "Achern", "w", DATE("1981-06-04")),
	VALUES("Siena", "Fuhrmann", "Freiburg", "w", DATE("1984-07-06")),
	VALUES("Julia", "Fink", "Lahr", "w", DATE("1985-08-05")),
	VALUES("Joseph", "Fischer", "Emmendingen", "m", DATE("1987-06-17")),
	VALUES("Alina", "Gans", "Waldkirch", "w", DATE("1986-05-15")),
	VALUES("Gerhard", "Göppert", "Freiburg", "m", DATE("1971-09-23")),
	VALUES("Philipp", "Groß", "Emmendingen", "m", DATE("1972-07-24")),
	VALUES("Katharina", "Gabriel", "Achern", "w", DATE("1970-11-23")),
	VALUES("Selina", "Dabanli", "Emmendingen", "w", DATE("1964-12-25")),
	VALUES("Oleg", "Hofer", "Offenburg", "m", DATE("1973-06-01")),
	VALUES("Layla", "Hefler", "Waldkirch", "w", DATE("1942-01-27")),
	VALUES("Rico", "Hemmer", "Lahr", "m", DATE("1935-01-08")),
	VALUES("Leonard", "Haubeil", "Emmendingen", "m", DATE("1948-02-09")),
	VALUES("Larissa", "Inntal", "Offenburg", "w", DATE("1949-03-11")),
	VALUES("Ludwig", "Jäger", "Waldkirch", "m", DATE("1951-04-21")),
	VALUES("Patricia", "Jobel", "Schutterwald", "w", DATE("1968-09-22")),
	VALUES("Janette", "Josephus", "Freiburg", "w", DATE("1997-02-28")),
	VALUES("Mirco", "Kammerdiener", "Offenburg", "m", DATE("1999-09-26")),
	VALUES("Günther", "Kross", "Lahr", "m", DATE("1951-02-08")),
	VALUES("Efraim", "Klein", "Lahr", "m", DATE("1966-01-29")),
	VALUES("Can", "Kind", "Achern", "m", DATE("1977-03-31")),
	VALUES("Simona", "Kunkel", "Freiburg", "w", DATE("1988-05-21")),
	VALUES("Tim", "Lehmann", "Schutterwald", "m", DATE("1999-07-29")),
	VALUES("Anita", "Lohrmann", "Offenburg", "w", DATE("1955-08-23")),
	VALUES("Anna", "Lahm", "Achern", "w", DATE("1967-10-16")),
	VALUES("Theodora", "Leber", "Emmendingen", "w", DATE("1962-12-17")),
	VALUES("Inge", "Lachmann", "Freiburg", "w", DATE("1983-04-18")),
	VALUES("Julia", "Merettig", "Offenburg", "w", DATE("1997-05-23")),
	VALUES("Hannes", "Huber", "Ohlsbach", "m", DATE("1998-01-02")),
	VALUES("Dora", "Mann", "Freiburg", "w", DATE("1996-08-06")),
	VALUES("Sarah", "Mogler", "Freiburg", "w", DATE("1974-08-09")),
	VALUES("Anna", "Michels", "Freiburg", "w", DATE("1954-07-13")),
	VALUES("Friedrich", "Schmidt", "Lahr", "m", DATE("1964-01-07")),
	VALUES("Lisa", "Neubert", "Waldkirch", "w", DATE("1962-06-13")),
	VALUES("Lena", "Nugen", "Lahr", "w", DATE("1953-02-05")),
	VALUES("John", "Opel", "Freiburg", "m", DATE("1953-03-14")),
	VALUES("Sophie", "Oragne", "Offenburg", "w", DATE("1962-03-14")),
	VALUES("Richard", "Ober", "Freiburg", "m", DATE("1978-03-14")),
	VALUES("Dania", "Polsko", "Offenburg", "w", DATE("1989-03-14")),
	VALUES("Daria", "Podolski", "Freiburg", "w", DATE("1997-03-14")),
	VALUES("Zoe", "Popolus", "Lahr", "w", DATE("1955-03-14")),
	VALUES("Athene", "Protz", "Offenburg", "w", DATE("1964-03-14")),
	VALUES("Christoph", "Portz", "Emmendingen", "m", DATE("1963-03-14")),
	VALUES("Christofer", "Postmann", "Offenburg", "m", DATE("1961-03-14")),
	VALUES("Alexander", "Rotmann", "Offenburg", "m", DATE("1953-03-14")),
	VALUES("Raphaela", "Ragen", "Offenburg", "w", DATE("1945-03-14")),
	VALUES("Tatjana", "Roggen", "Lahr", "w", DATE("1946-03-14")),
	VALUES("Alisa", "Reber", "Offenburg", "w", DATE("1947-03-14")),
	VALUES("Audrey", "Rupps", "Waldkirch", "w", DATE("1958-03-14")),
	VALUES("Lea", "Rupps", "Offenburg", "w", DATE("1969-03-14")),
	VALUES("Alina", "Lehmann", "Emmendingen", "w", DATE("1940-03-14")),
	VALUES("Raphael", "Rotweiler", "Offenburg", "m", DATE("1936-03-14")),
	VALUES("Jakob", "Rastätter", "Waldkirch", "m", DATE("1934-03-14")),
	VALUES("Josef", "Sillmann", "Freiburg", "m", DATE("1945-03-14")),
	VALUES("Maria", "Schmidt", "Emmendingen", "w", DATE("1952-03-14")),
	VALUES("Tom", "Schmidt", "Offenburg", "m", DATE("1964-03-14")),
	VALUES("Lina", "Schmitt", "Lahr", "w", DATE("1975-03-14")),
	VALUES("Luke", "Schmieder", "Offenburg", "m", DATE("2002-03-14")),
	VALUES("Simon", "Schmuggler", "Freiburg", "m", DATE("2003-03-14")),
	VALUES("Olivia", "Stiefel", "Emmendingen", "w", DATE("2000-03-14")),
	VALUES("Tabea", "Singer", "Waldkirch", "w", DATE("2000-03-14")),
	VALUES("Beatrice", "Sauer", "Freiburg", "w", DATE("2005-03-14")),
	VALUES("Tobias", "Sauter", "Lahr", "m", DATE("2006-03-14")),
	VALUES("Savanna", "Turm", "Lahr", "w", DATE("2010-03-14")),
	VALUES("Stella", "Trost", "Lahr", "w", DATE("2012-03-14")),
	VALUES("Florian", "Tummler", "Freiburg", "m", DATE("2004-03-14")),
	VALUES("Armin", "Treuer", "Offenburg", "m", DATE("2005-03-14")),
	VALUES("Brandon", "Tilsitter", "Offenburg", "m", DATE("2009-03-14")),
	VALUES("Niklas", "Ullmann", "Offenburg", "m", DATE("2008-03-14")),
	VALUES("Erika", "Urs", "Emmendingen", "w", DATE("2007-03-14")),
	VALUES("Bojan", "Ungrau", "Freiburg", "m", DATE("1944-03-14")),
	VALUES("Marcel", "Uhl", "Offenburg", "m", DATE("1955-03-14")),
	VALUES("Timo", "Uhrmacher", "Offenburg", "m", DATE("1956-03-14")),
	VALUES("Tino", "Vallis", "Offenburg", "m", DATE("1967-03-14")),
	VALUES("Rosalie", "Vadung", "Offenburg", "w", DATE("1958-03-14")),
	VALUES("Lars", "Weber", "Lahr", "m", DATE("1949-03-14")),
	VALUES("Johann", "Wöhner", "Offenburg", "m", DATE("1950-03-14")),
	VALUES("Stephan", "Wegner", "Freiburg", "m", DATE("1939-03-14")),
	VALUES("Stefanie", "Waber", "Lahr", "w", DATE("1945-03-14")),
	VALUES("Sabrina", "Wagner", "Offenburg", "w", DATE("1946-03-14")),
	VALUES("Anna", "Wagner", "Offenburg", "w", DATE("1955-03-14")),
	VALUES("Alena", "Yang", "Offenburg", "w", DATE("1958-03-14")),
	VALUES("Maria", "Zimmermann", "Emmendingen", "w", DATE("1967-03-14"));
INSERT INTO Users(PersonID, Benutzername, Rechte, Passwort) 
	VALUES((Select PersonID FROM Person WHERE Vorname = "Janes" AND Nachname = "Heuberger"), "Janessus", "Admin", "password"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Hannes" AND Nachname = "Huber"), "Buma11", "Admin", "123456"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Julia" AND Nachname = "Merettig"), "Schokokeks", "Admin", "schokolade"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Friedrich" AND Nachname = "Schmidt"), "Zett94", "Admin", "keineahnung"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Klaus" AND Nachname = "Arendt"), "Klausimausi", "Standard", "bestespw"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Joachim" AND Nachname = "Adam"), "TheLegend27", "Standard", "TheLegend27"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Thomas" AND Nachname = "Adolf"), "ForeverAfd", "Standard", "kriegisbest"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Liliane" AND Nachname = "Bauer"), "LandlebenFTW", "Standard", "Traktor6"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Lukas" AND Nachname = "Brau"), "BierLover66", "Standard", "Urquell"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Samuel" AND Nachname = "Burg"), "Lancelot", "Standard", "Arthurftw"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Matthias" AND Nachname = "Bruggmoser"), "TheBeast", "Standard", "sicherespw"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Arianna" AND Nachname = "Adari"), "PingPongShowMaster", "Standard", "Atariftw"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Arion" AND Nachname = "Cern"), "TeilchenMaster", "Standard", "LHCisthebest"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Brigitte" AND Nachname = "Dahlmann"), "Kittielover", "Standard", "Nicenstein"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Bruno" AND Nachname = "Danner"), "BlackDragon", "Standard", "DannerSwag"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Doreen" AND Nachname = "Dannecker"), "RefrendaryLive", "Standard", "badGrades"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Dan" AND Nachname = "Erdmann"), "Maulwurf72", "Standard", "DerWühler"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Elena" AND Nachname = "Emmenecker"), "Leichtathletikfreak", "Standard", "Hürdenmaster"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Irina" AND Nachname = "Freud"), "Psychomaster", "Standard", "PenisNeid"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Siena" AND Nachname = "Fuhrmann"), "PastaFetisch", "Standard", "PizzaLove"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Julia" AND Nachname = "Fink"), "Vogelbaby", "Standard", "Eierleger"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Joseph" AND Nachname = "Fischer"), "JavaHater", "Standard", "CMasterrace"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Alina" AND Nachname = "Gans"), "Federkleid", "Standard", "Schnabel21"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Gerhard" AND Nachname = "Göppert"), "GrowThatShit", "Standard", "420"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Philipp" AND Nachname = "Groß"), "ThormundGiantsbane", "Standard", "MilkIsLove"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Katharina" AND Nachname = "Gabriel"), "Archangel", "Standard", "DadIsGod"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Selina" AND Nachname = "Dabanli"), "Hottie47", "Standard", "LoveMe"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Oleg" AND Nachname = "Hofer"), "Viking1", "Standard", "OdinIsBest"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Layla" AND Nachname = "Hefler"), "BunnyFreak", "Standard", "Playboymaster"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Rico" AND Nachname = "Hemmer"), "NailsBow", "Standard", "IPunch"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Leonard" AND Nachname = "Haubeil"), "AxesUnite", "Standard", "ChopTheTrees"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Larissa" AND Nachname = "Inntal"), "BadGirl26", "Standard", "IWreckYou"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Ludwig" AND Nachname = "Jäger"), "GunsAreLife", "Standard", "Intervention"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Patricia" AND Nachname = "Jobel"), "FreiburgBest", "Standard", "StuttgartWorst"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Janette" AND Nachname = "Josephus"), "Jesus2873", "Standard", "BowBeforeHim"),
	VALUES((Select PersonID FROM Person WHERE Vorname = "Mirco" AND Nachname = "Kammerdiener"), "TheSlave", "Standard", "Shackles"),
	
	
	
	
	
	
	
	
	
	
	
	
	INSERT INTO Zimmer(StationStationsbezeichnung, ZimmerNr)
	VALUES("Gynäkologie", 1),
	VALUES("Gynäkologie", 2),
	VALUES("Gynäkologie", 3),
	VALUES("Gynäkologie", 4),
	VALUES("Gynäkologie", 5),
	VALUES("Gynäkologie", 6),
	VALUES("Gynäkologie", 7),
	VALUES("Gynäkologie", 8),
	VALUES("Gynäkologie", 9),
	VALUES("Gynäkologie", 10),
	VALUES("Gynäkologie", 11),
	VALUES("Gynäkologie", 12),
	VALUES("Gynäkologie", 13),
	VALUES("Gynäkologie", 14),
	VALUES("Gynäkologie", 15),
	VALUES("Gynäkologie", 16),
	VALUES("Gynäkologie", 17),
	VALUES("Gynäkologie", 18),
	VALUES("Gynäkologie", 19),
	VALUES("Gynäkologie", 20),
	VALUES("Gynäkologie", 21),
	VALUES("Gynäkologie", 22),
	VALUES("Gynäkologie", 23),
	VALUES("Gynäkologie", 24),
	VALUES("Gynäkologie", 25),
	VALUES("innere Medizin", 1),
	VALUES("innere Medizin", 2),
	VALUES("innere Medizin", 3),
	VALUES("innere Medizin", 4),
	VALUES("innere Medizin", 5),
	VALUES("innere Medizin", 6),
	VALUES("innere Medizin", 7),
	VALUES("innere Medizin", 8),
	VALUES("innere Medizin", 9),
	VALUES("innere Medizin", 10),
	VALUES("innere Medizin", 11),
	VALUES("innere Medizin", 12),
	VALUES("innere Medizin", 13),
	VALUES("innere Medizin", 14),
	VALUES("innere Medizin", 15),
	VALUES("innere Medizin", 16),
	VALUES("innere Medizin", 17),
	VALUES("innere Medizin", 18),
	VALUES("innere Medizin", 19),
	VALUES("innere Medizin", 20),
	VALUES("innere Medizin", 21),
	VALUES("innere Medizin", 22),
	VALUES("innere Medizin", 23),
	VALUES("innere Medizin", 24),
	VALUES("innere Medizin", 25),
	VALUES("Onkologie", 1),
	VALUES("Onkologie", 2),
	VALUES("Onkologie", 3),
	VALUES("Onkologie", 4),
	VALUES("Onkologie", 5),
	VALUES("Onkologie", 6),
	VALUES("Onkologie", 7),
	VALUES("Onkologie", 8),
	VALUES("Onkologie", 9),
	VALUES("Onkologie", 10),
	VALUES("Onkologie", 11),
	VALUES("Onkologie", 12),
	VALUES("Onkologie", 13),
	VALUES("Onkologie", 14),
	VALUES("Onkologie", 15),
	VALUES("Onkologie", 16),
	VALUES("Onkologie", 17),
	VALUES("Onkologie", 18),
	VALUES("Onkologie", 19),
	VALUES("Onkologie", 20),
	VALUES("Onkologie", 21),
	VALUES("Onkologie", 22),
	VALUES("Onkologie", 23),
	VALUES("Onkologie", 24),
	VALUES("Onkologie", 25),
	VALUES("Orthopädie", 1),
	VALUES("Orthopädie", 2),
	VALUES("Orthopädie", 3),
	VALUES("Orthopädie", 4),
	VALUES("Orthopädie", 5),
	VALUES("Orthopädie", 6),
	VALUES("Orthopädie", 7),
	VALUES("Orthopädie", 8),
	VALUES("Orthopädie", 9),
	VALUES("Orthopädie", 10),
	VALUES("Orthopädie", 11),
	VALUES("Orthopädie", 12),
	VALUES("Orthopädie", 13),
	VALUES("Orthopädie", 14),
	VALUES("Orthopädie", 15),
	VALUES("Orthopädie", 16),
	VALUES("Orthopädie", 17),
	VALUES("Orthopädie", 18),
	VALUES("Orthopädie", 19),
	VALUES("Orthopädie", 20),
	VALUES("Orthopädie", 21),
	VALUES("Orthopädie", 22),
	VALUES("Orthopädie", 23),
	VALUES("Orthopädie", 24),
	VALUES("Orthopädie", 25),
	VALUES("Pädiatrie", 1),
	VALUES("Pädiatrie", 2),
	VALUES("Pädiatrie", 3),
	VALUES("Pädiatrie", 4),
	VALUES("Pädiatrie", 5),
	VALUES("Pädiatrie", 6),
	VALUES("Pädiatrie", 7),
	VALUES("Pädiatrie", 8),
	VALUES("Pädiatrie", 9),
	VALUES("Pädiatrie", 10),
	VALUES("Pädiatrie", 11),
	VALUES("Pädiatrie", 12),
	VALUES("Pädiatrie", 13),
	VALUES("Pädiatrie", 14),
	VALUES("Pädiatrie", 15),
	VALUES("Pädiatrie", 16),
	VALUES("Pädiatrie", 17),
	VALUES("Pädiatrie", 18),
	VALUES("Pädiatrie", 19),
	VALUES("Pädiatrie", 20),
	VALUES("Pädiatrie", 21),
	VALUES("Pädiatrie", 22),
	VALUES("Pädiatrie", 23),
	VALUES("Pädiatrie", 24),
	VALUES("Pädiatrie", 25),
	VALUES("Intensivstation", 1),
	VALUES("Intensivstation", 2),
	VALUES("Intensivstation", 3),
	VALUES("Intensivstation", 4),
	VALUES("Intensivstation", 5),
	VALUES("Intensivstation", 6),
	VALUES("Intensivstation", 7),
	VALUES("Intensivstation", 8),
	VALUES("Intensivstation", 9),
	VALUES("Intensivstation", 10);
	
